### ISSUE TITLE
cut-copy-paste / undo-redo are not available on app

### ISSUE THREAD

**Issue by iX315** [dsheiko/puppetry#2]
The keyboard shortcuts on title are unavailable on Mac OS X

OS: 10.13.6 (17G65)
APP: v1.0.0

**Comment by dsheiko** [comment]
Thank you! You are right, the menu displayed shortcuts for Win/Linux, but should show Command instead of Ctrl. I fixed it in
https://github.com/dsheiko/puppetry/commit/b4e41ec5b80b0cb67db5554f3309274484d6d57e
I'm going to release 1.0.1 on Monday

**Comment by mortocks** [comment]
I'm running v1.0.1 on osx and the cut-copy-paste keyboard shortcuts still don't work.

**Comment by mortocks** [comment]
Copy and pasting into any of the text fields e.g. pasting selectors from the browser into the selector text boxes (plus any other text fields)

<img width="972" alt="fields" src="https://user-images.githubusercontent.com/314196/49643840-7fa41980-fa62-11e8-82d6-ac0533732752.png">

**Comment by mortocks** [comment]
cmd + c, cmd + v ( not p obviously :p )

**Comment by dsheiko** [comment]
Hmm, you are right... I'm gonna investigate

**Comment by dsheiko** [comment]
Yeah, I was attentive enough on first fix, actually fixed other short-cuts. Now pushing a new one for copy/paste

**Comment by dsheiko** [comment]
The fix available  since https://github.com/dsheiko/puppetry/releases/tag/v1.0.3
